ALTER TABLE Usuario ADD PRIMARY KEY (UsuarioID);
ALTER TABLE Cliente ADD PRIMARY KEY (ClienteID);
ALTER TABLE Pedido ADD PRIMARY KEY (PedidoID);
ALTER TABLE UsuarioRol ADD PRIMARY KEY (UsuarioRolID);
ALTER TABLE EstadoPedido ADD PRIMARY KEY (EstadoPedidoID);
ALTER TABLE Producto ADD PRIMARY KEY (ProductoID);
ALTER TABLE TipoCliente ADD PRIMARY KEY (TipoClienteID);
